### PR TITLE
fix(logger): Drop bad messages instead of panicking

### LINKED ISSUE #24: Dont panic on malformed log messages
https://github.com/deis/logger/blame/master/syslogish/server.go#L112

### PR DESCRIPTION
**Pull request by krancour**
Fixes #24

### CODE REVIEW

File: syslogish/server.go [hunk 1]
```diff
@@ -106,13 +106,9 @@ func (s *Server) receive() {
...
 		}
-		rawMessage := strings.TrimSuffix(string(buf[:n]), "\n")
-		// We want to strip off all the leading syslog junk but there is no good way to do that.
-		// So we split the string on the leading "{" but we have to add it back so we can parse the log message into a map
-		logMessage := "{" + strings.SplitAfterN(rawMessage, "{", 2)[1]
-
+		message := strings.TrimSuffix(string(buf[:n]), "\n")
 		select {
-		case s.storageQueue <- logMessage:
+		case s.storageQueue <- message:
```
Comment (arschles) [inline syslogish/server.go]: is it worth waiting for a short duration here instead of immediately bailing on the send?

File: syslogish/server.go [hunk 2]
```diff
@@ -120,46 +116,56 @@ func (s *Server) receive() {
...
+		curlyIndex := strings.Index(message, "{")
+		if curlyIndex > -1 {
+			message = message[curlyIndex:]
+			// Parse the message into json
+			var messageJSON map[string]interface{}
+			err := json.Unmarshal([]byte(message), &messageJSON)
+			// We sometimes get log messages that do not conform to the structure we expect.
+			// So we will check that the kubernetes key exists so that we dont error out.
+			if err == nil && messageJSON["kubernetes"] != nil &&
+				messageJSON["kubernetes"].(map[string]interface{})["labels"] != nil {
```
Comment (arschles) [inline syslogish/server.go]: why do you need the type assertion here? looks like `messageJSON` is already a `map[string]interface{}`

File: syslogish/server.go [hunk 3]
```diff
@@ -120,46 +116,56 @@ func (s *Server) receive() {
...
+				labels := messageJSON["kubernetes"].(map[string]interface{})["labels"].(map[string]interface{})
```
Comment (arschles) [inline syslogish/server.go]: same here RE the type assertion

File: syslogish/server.go [hunk 4]
```diff
@@ -120,46 +116,56 @@ func (s *Server) receive() {
...
+					// configurer in the time between we check if it's nil and the time we invoke .Write()
+					// upon it.
+					s.adapterMutex.RLock()
+					// DONT'T defer unlocking... defered statements are executed when the function returns,
+					// but we are inside an infinite loop here.  If we defer, we would never release the
+					// lock.  Instead, release it manually below.
+					if s.storageAdapter != nil {
+						app := labels["app"].(string)
+						body := messageJSON["log"].(string)
+						podName := messageJSON["kubernetes"].(map[string]interface{})["pod_name"].(string)
```
Comment (arschles) [inline syslogish/server.go]: same here RE the type assertion

File: syslogish/server.go [hunk 5]
```diff
@@ -120,46 +116,56 @@ func (s *Server) receive() {
...
+					// Get a read lock to ensure the storage adapater pointer can't be nilled by the
+					// configurer in the time between we check if it's nil and the time we invoke .Write()
+					// upon it.
+					s.adapterMutex.RLock()
+					// DONT'T defer unlocking... defered statements are executed when the function returns,
+					// but we are inside an infinite loop here.  If we defer, we would never release the
+					// lock.  Instead, release it manually below.
+					if s.storageAdapter != nil {
+						app := labels["app"].(string)
+						body := messageJSON["log"].(string)
```
Comment (arschles) [inline syslogish/server.go]: this and the above type assertion should be checked

File: syslogish/server.go [hunk 6]
```diff
@@ -120,46 +116,56 @@ func (s *Server) receive() {
...
+						// even more log messages to STDOUT.  The overall effect would be the same as described
+						// above with the added disadvantages of flapping.
+					}
+					s.adapterMutex.RUnlock()
+					// Add the message to the drainage queue.  This allows the storage loop to continue right
+					// away instead of waiting while the message is sent to an external service-- since that
+					// could be a bottleneck and error prone depending on rate limiting, network congestion,
+					// etc.
+					select {
+					case s.drainageQueue <- message:
```
Comment (arschles) [inline syslogish/server.go]: same question here regarding waiting to send for a short duration instead of bailing immediately

File: syslogish/server.go (hunk 1 above)
Comment (krancour) [inline syslogish/server.go]: I'm honestly not sure.  The _original_ intent of this code was to dump messages into a channel as fast as possible to avoid the UDP stack's own internal queue filling up and dropping _new_ incoming messages.  So if and when the queue backs up, the scheme basically favors _new_ messages that we might still be able to process over the one we have in hand right now.

Are there better ways to deal with this?  Probably.  But since the behavior isn't really changed by the PR, that should probably be a separate issue if it's worthy of further investigation.

File: syslogish/server.go (hunk 2 above)
Comment (krancour) [inline syslogish/server.go]: Not sure why that was done.  It is probably an oversite.  It should be fixed in a separate PR.

I know you already have realized this, but for the benefit of anyone else reading these comments, many of these green lines aren't changes, but they appear in the diff only because they got indented one level extra because of a new conditional surrounding them.

File: syslogish/server.go (hunk 6 above)
Comment (krancour) [inline syslogish/server.go]: The drain code is actually not used and will be removed in a separate PR.  See #30

File: syslogish/server.go (hunk 1 above)
Comment (arschles) [inline syslogish/server.go]: >that should probably be a separate issue if it's worthy of further investigation

Sounds good to me. But, since we're trying to send as fast as possible and avoid queue buildup, and we're ok dropping messages (these eventually end up as UDP packages, so I'm assuming...), I bet this is fine as-is.

File: syslogish/server.go (hunk 2 above)
Comment (arschles) [inline syslogish/server.go]: >It should be fixed in a separate PR

Sounds good

File: syslogish/server.go (hunk 6 above)
Comment (arschles) [inline syslogish/server.go]: ok, sounds good

**Comment by arschles** [comment]
@krancour marked LGTM1. Looks like all my comments have been addressed (almost all of them were on code that you actually didn't modify - just changed spacing on). Thanks for creating issues to track each comment.

File: syslogish/server.go (hunk 5 above)
Comment (krancour) [inline syslogish/server.go]: Not introduced by this PR, but agreed.  Opened #34
