### PR TITLE
fix(logger): reduce CPU/memory usage

### LINKED ISSUE #102: Logger excessive CPU usage
I'm running deis workflow v2.3.0 with logger v2.2.0 and I noticed that the logger process is consistently eating up over 60% cpu time on a dual core m4 large instance.

Given that the whole cluster is a staging environment that is basically idle, this seems quite extreme…

The cluster consists of a t2.small controller (1 vCPU, 2GB) and two m4.large nodes (2 vCPU 8GB) running CoreOS stable 1068.9.0 and K8s v1.3.4.

### LINKED ISSUE #104: Logger memory leak
Looks like logger may be leaking a couple MiB/hr

2016-08-25 at 09 46

### PR DESCRIPTION
**Pull request by bacongobbler**
The way we spawned and checked to ensure the weblog server was running was a bit backwards,
causing the logger to run with massive CPU usage after a few hours because of the state loop.
Changing the server logic to instead defer to net/http for serving requests and shutting down
the connection at the net.Listener reduces CPU usage significantly.

Additionally the Redis adapter had a similar issue; creating connections, writing every second, never close the connection and re-initiate a new connection. Re-using the connection will reduce CPU cycle usage significantly.

TESTING:

 - deploy this image on top of workflow-dev
 - run `kubectl exec -it deis-logger-asdfsf top`

CPU usage should now be observed much lower than it was before.

closes #102
closes #104

### CODE REVIEW

**Comment by bacongobbler** [comment]
I'm still seeing 6.7% spikes even at idle... Must be something else

File: storage/redis_adapter.go [hunk 1]
```diff
@@ -54,12 +54,9 @@ func (mp messagePipeliner) execPipeline() {
...
 	}
-	go func() {
-		defer mp.pipeline.Close()
-		if _, err := mp.pipeline.Exec(); err != nil {
-			mp.errCh <- fmt.Errorf("Error executing pipeline: %s", err)
-		}
-	}()
+	if _, err := mp.pipeline.Exec(); err != nil {
+		mp.errCh <- fmt.Errorf("Error executing pipeline: %s", err)
+	}
```
Comment (krancour) [inline storage/redis_adapter.go]: This was deliberately being executed as a goroutine-- because there's no reason for this code to block on pipeline execution.

File: weblog/server.go [hunk 2]
```diff
@@ -2,49 +2,60 @@ package weblog
...
-		router: newRouter(newRequestHandler(storageAdapter)),
-	}, nil
+// New returns a new HTTP Server and starts it.
+// The caller should call Close when finished to shut it down.
+func NewServer(storageAdapter storage.Adapter) *Server {
+	s := &Server{
+		Listener: defaultListener(),
+		Config:   &http.Server{Handler: newRouter(newRequestHandler(storageAdapter))},
+	}
+	s.Start()
```
Comment (krancour) [inline weblog/server.go]: fwiw, I think it's odd (bad, IMO) to implicitly "start" things upon creation, especially when you require that thing to be explicitly _stopped_ / closed. It's easy to forget to defer a stop or close... it's easier to remember to do when you have to explicitly invoke start, listen, etc.

File: storage/redis_adapter.go (hunk 1 above)
Comment (bacongobbler) [inline storage/redis_adapter.go]: see line 115.

File: weblog/server.go (hunk 2 above)
Comment (bacongobbler) [inline weblog/server.go]: fixed up. I agree that we shouldn't start things upon creation. I'm going to refactor the Start code a bit so it doesn't call `panic` here

**Comment by bacongobbler** [comment]
OK, let's hope the Redis changes fixes things. @jeroenvisser101 confirmed that switching storage adapters reduced CPU usage, and since it happens even when the logger is "idling" I have to assume it's something in the control loop.

**Comment by jeroenvisser101** [comment]
@bacongobbler if you've got time, I can deploy this into production and we can do tests there? Let me know :)

**Comment by jeroenvisser101** [comment]
btw, it still shows `./main.go:36: undefined: s in s.Start` in jenkins, but if it's ready to test, just ping me on slack or here, and we'll be able to test it in prod.

**Comment by bacongobbler** [comment]
I'm still testing this myself. Once it's ready for others to review I'll label it as such :)

**Comment by jeroenvisser101** [comment]
Nice, thanks!

**Comment by bacongobbler** [comment]
> 2016/09/13 23:59:55 Error executing pipeline: redis: client is closed

d'oh.

**Comment by bacongobbler** [comment]
Looks like everything passed except for codecov so this is ready for review!

**Comment by mboersma** [comment]
This is 💚  now, but it didn't have unit tests to cover the new code introduced. Is it reasonable to add coverage in `logger_test.go` or elsewhere?

**Comment by bacongobbler** [comment]
Absolutely. I'll add some logger unit tests in here as well.

**Comment by jchauncey** [comment]
@bacongobbler ive installed this on my cluster will let it run the weekend

**Comment by bacongobbler** [comment]
Hey @jchauncey any update on your cluster's state? Just about to bring one up myself as you can see CPU spikes even after 5 minutes of running.

**Comment by felixbuenemann** [comment]
@bacongobbler Looking good here as well. I had the new build running over the weekend and it's at roughly 0% CPU and 10 MB RSS. ❤️

**Comment by bacongobbler** [comment]
@mboersma I just added a massive load of server tests, let me know if you'd like to see redis adapter tests as well and I'll re-label this as necessary.

**Comment by jeroenvisser101** [comment]
Roughly the same here! Screenshot

**Comment by jchauncey** [comment]
@bacongobbler ready to merge
